-- 코드를 입력하세요
(SELECT DATE_FORMAT(O.SALES_DATE,'%Y-%m-%d') AS SALES_DATE , O.PRODUCT_ID, O.USER_ID, O.SALES_AMOUNT
FROM ONLINE_SALE O
WHERE O.SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31')

UNION ALL

(SELECT  DATE_FORMAT(F.SALES_DATE,'%Y-%m-%d') AS SALES_DATE , F.PRODUCT_ID, NULL , F.SALES_AMOUNT
FROM OFFLINE_SALE F
WHERE F.SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31')

ORDER BY SALES_DATE, PRODUCT_ID, USER_ID