-- 코드를 입력하세요
SELECT p.PRODUCT_ID, p.PRODUCT_NAME, SUM(AMOUNT) * PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT p, FOOD_ORDER o
WHERE p.PRODUCT_ID = o.PRODUCT_ID AND DATE_FORMAT(o.PRODUCE_DATE,'%Y-%m') = '2022-05'
GROUP BY p.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, p.PRODUCT_ID 