-- # -- 코드를 입력하세요
-- # SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE, PRODUCT_NAME
-- # FROM FOOD_PRODUCT
-- # GROUP BY CATEGORY
-- # HAVING CATEGORY = '과자' or CATEGORY = '국' or CATEGORY = '김치' or CATEGORY = '식용유'
-- # ORDER BY MAX_PRICE DESC


SELECT CATEGORY,PRICE AS MAX_PRICE,PRODUCT_NAME
FROM (
    SELECT *
    FROM FOOD_PRODUCT f1
    WHERE PRICE >= ALL 
    (
    SELECT PRICE
    FROM FOOD_PRODUCT f2
    WHERE f1.CATEGORY = f2.CATEGORY)
    
    GROUP BY CATEGORY
    HAVING CATEGORY IN ('과자','국','김치','식용유')
) A
ORDER BY MAX_PRICE DESC