-- 코드를 입력하세요
SELECT MEMBER_NAME,REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE m,REST_REVIEW r
WHERE m.MEMBER_ID IN
    (SELECT m.MEMBER_ID
    FROM MEMBER_PROFILE m , REST_REVIEW r
    WHERE m.MEMBER_ID = r.MEMBER_ID
    GROUP BY r.MEMBER_ID
    HAVING COUNT(*) >= ALL (
        SELECT COUNT(*)
        FROM MEMBER_PROFILE m , REST_REVIEW r
        WHERE m.MEMBER_ID = r.MEMBER_ID
        GROUP BY r.MEMBER_ID
    ) 
) AND m.MEMBER_ID = r.MEMBER_ID

ORDER BY REVIEW_DATE, REVIEW_TEXT