-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH,GENDER, COUNT(DISTINCT s.USER_ID) AS USERS
FROM USER_INFO u, ONLINE_SALE s
WHERE u.USER_ID = s.USER_ID
GROUP BY DATE_FORMAT(SALES_DATE,'%Y-%m'), GENDER
HAVING GENDER is not NULL
ORDER BY YEAR,MONTH,GENDER



-- DATE_FORMAT 쓰면 왜 안됨? replace로 0도 지웠는데!!!
--엥 replace로 0을 안지우면 정답입니다 뜸;; 뭥미?
-- SELECT DATE_FORMAT(SALES_DATE,'%Y') AS YEAR, REPLACE(DATE_FORMAT(SALES_DATE,'%m'),0,'') AS MONTH,GENDER, COUNT(DISTINCT s.USER_ID) AS USERS
-- FROM USER_INFO u, ONLINE_SALE s
-- WHERE u.USER_ID = s.USER_ID
-- GROUP BY DATE_FORMAT(SALES_DATE,'%Y-%m'), GENDER
-- HAVING GENDER is not NULL
-- ORDER BY YEAR,MONTH,GENDER
