-- # -- 코드를 입력하세요
-- # SELECT p.PRODUCT_CODE , (p.PRICE * o.SALES_AMOUNT) AS SALES
-- # FROM PRODUCT p , OFFLINE_SALE o
-- # WHERE p.PRODUCT_ID = o.PRODUCT_ID
-- # ORDER BY SALES DESC, p.PRODUCT_ID

SELECT PRODUCT_CODE, (SUM(o.SALES_AMOUNT) * p.PRICE) AS SALES
FROM PRODUCT p , OFFLINE_SALE o
WHERE p.PRODUCT_ID = o.PRODUCT_ID
GROUP BY o.PRODUCT_ID
ORDER BY SALES DESC, p.PRODUCT_CODE