-- 코드를 입력하세요

SELECT A.CAR_ID, '대여 가능' AS AVAILABILITY
FROM(
SELECT DISTINCT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY

EXCEPT 

SELECT DISTINCT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE_FORMAT(END_DATE,'%Y-%m-%d') >= '2022-10-16' AND DATE_FORMAT(START_DATE,'%Y-%m-%d') <= '2022-10-16' 
) A

UNION

SELECT DISTINCT CAR_ID, '대여중'
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE_FORMAT(END_DATE,'%Y-%m-%d') >= '2022-10-16' AND DATE_FORMAT(START_DATE,'%Y-%m-%d') <= '2022-10-16'

ORDER BY CAR_ID DESC


##########################################################

-- 코드를 입력하세요

SELECT DISTINCT CAR_ID,
    MAX(CASE
        WHEN DATE_FORMAT(END_DATE,'%Y-%m-%d') >= '2022-10-16' AND DATE_FORMAT(START_DATE,'%Y-%m-%d') <= '2022-10-16'
        THEN '대여중'
        ELSE '대여 가능'
    END) AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC