-- 코드를 입력하세요
SELECT FOOD_TYPE,REST_ID,REST_NAME,FAVORITES
FROM REST_INFO r
WHERE r.FAVORITES >= ALL(
    SELECT r2.FAVORITES
    FROM REST_INFO r2
    WHERE r.FOOD_TYPE = r2.FOOD_TYPE
)
ORDER BY FOOD_TYPE DESC